name: Schedule Colab Script

on:
  schedule:
    # Запуск в 9 утра и 9 вечера по UTC
    - cron: '0 10,22 * * *'

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
          pip install google-auth requests pandas google-api-python-client

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute _200.ipynb --output result.ipynb
