name: Планирование скриптов для vitrina24.kz и med.vitrina24.kz

on:
  schedule:
    - cron: '0 7,19 * * *'  # Запуск в 7 утра и 7 вечера по UTC для med.vitrina24.kz
    - cron: '0 8,20 * * *'  # Запуск в 8 утра и 8 вечера по UTC для vitrina24.kz

jobs:
  run-colab-medvitrina:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
          pip install google-auth requests pandas google-api-python-client beautifulsoup4 lxml

      - name: Выполнение Jupyter Notebook для med.vitrina24.kz
        run: |
          jupyter nbconvert --to notebook --execute index_medvitrina__200.ipynb --output result_medvitrina.ipynb

      - name: Сохранение лог-файла для med.vitrina24.kz
        uses: actions/upload-artifact@v2
        with:
          name: medvitrina-log
          path: /content/drive/MyDrive/Colab Notebooks/indexing_log_medvitrina.txt

  run-colab-vitrina24:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
          pip install google-auth requests pandas google-api-python-client beautifulsoup4 lxml

      - name: Выполнение Jupyter Notebook для vitrina24.kz
        run: |
          jupyter nbconvert --to notebook --execute index_vitrina__200.ipynb --output result_vitrina24.ipynb

      - name: Сохранение лог-файла для vitrina24.kz
        uses: actions/upload-artifact@v2
        with:
          name: vitrina24-log
          path: /content/drive/MyDrive/Colab Notebooks/indexing_log_vitrina24.txt
