name: Планировщик скриптов для vitrina24.kz и med.vitrina24.kz

on:
  schedule:
    - cron: '0 8,20 * * *'  # Запуск в 8 утра и 8 вечера UTC для med.vitrina24.kz
    - cron: '0 9,21 * * *'  # Запуск в 9 утра и 9 вечера UTC для vitrina24.kz

jobs:
  run-medvitrina24:
    runs-on: ubuntu-latest
    name: Выполнение index_medvitrina__200.ipynb
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2

      - name: Настройка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
          pip install google-auth requests pandas google-api-python-client beautifulsoup4 lxml

      - name: Выполнение index_medvitrina__200.ipynb
        run: |
          jupyter nbconvert --to notebook --execute index_medvitrina__200.ipynb --output result_medvitrina24.ipynb

      - name: Отправка уведомления о запуске в Telegram
        run: python send_telegram_message.py '/content/gdrive/MyDrive/Colab Notebooks/tgtokenvitrina24kz.txt' '-1002207415181' 'Запущен планировщик на индекс med.vitrina24.kz'

      - name: Сохранение файла журнала
        uses: actions/upload-artifact@v2
        with:
          name: script-log
          path: /content/drive/MyDrive/Colab Notebooks/indexing_log_medvitrina24.txt

  run-vitrina24:
    runs-on: ubuntu-latest
    name: Выполнение index_vitrina__200.ipynb
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2

      - name: Настройка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
          pip install google-auth requests pandas google-api-python-client beautifulsoup4 lxml

      - name: Выполнение index_vitrina__200.ipynb
        run: |
          jupyter nbconvert --to notebook --execute index_vitrina__200.ipynb --output result_vitrina24.ipynb

      - name: Отправка уведомления о запуске в Telegram
        run: python send_telegram_message.py '/content/gdrive/MyDrive/Colab Notebooks/tgtokenvitrina24kz.txt' '-1002207415181' 'Запущен планировщик на индекс vitrina24.kz'

      - name: Сохранение файла журнала
        uses: actions/upload-artifact@v2
        with:
          name: script-log
          path: /content/drive/MyDrive/Colab Notebooks/indexing_log_vitrina24.txt
