name: Schedule Scripts for med.vitrina24.kz

on:
  schedule:
    - cron: '0 13,1 * * *'  # Запуск в 13:00 и 01:00

jobs:
  run-script-medvitrina24:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
          pip install google-auth requests pandas google-api-python-client beautifulsoup4 lxml

      - name: Execute Jupyter Notebook for med.vitrina24.kz
        run: |
          jupyter nbconvert --to notebook --execute index_medvitrina__200.ipynb --output result_medvitrina.ipynb

      - name: Save log file for med.vitrina24.kz
        uses: actions/upload-artifact@v2
        with:
          name: script-log-medvitrina
          path: /content/drive/MyDrive/Colab Notebooks/indexing_log_medvitrina.txt
