name: Schedule Scripts

on:
  schedule:
    - cron: '0 13 * * *'   # Запуск в 13:00 UTC (для мед витрины)
    - cron: '0 1 * * *'    # Запуск в 01:00 UTC (для мед витрины)

jobs:
  run-medvitrina24-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main  # Указываете ветку, если это необходимо

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Добавьте дополнительные шаги для выполнения скрипта мед витрина здесь
