name: Execute MedVitrina24 script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Запускать каждый день в полночь UTC

jobs:
  run-medvitrina24-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Указать версию Python, если необходимо

      - name: Install Jupyter
        run: |
          python -m pip install --upgrade pip
          pip install jupyter

      - name: Execute notebook with nbconvert
        run: |
          jupyter nbconvert --to notebook --execute index_medvitrina__200.ipynb --output result_medvitrina24.ipynb --ExecutePreprocessor.kernel_name=python3

      - name: Save and commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add result_medvitrina24.ipynb
          git commit -m "Auto-generated notebook result"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
