name: Run MedVitrina24 Script
on:
  schedule:
    - cron: '0 13,1 * * *'  # Запуск в 13:00 и 01:00 каждый день

jobs:
  run-medvitrina24-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Указать версию Python, если необходимо

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Замените на установку необходимых пакетов
      
      - name: Execute MedVitrina24 script
        run: |
          jupyter nbconvert --to notebook --execute index_medvitrina__200.ipynb --output result_medvitrina24.ipynb --ExecutePreprocessor.kernel_name=python3

      - name: Save and commit results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add result_medvitrina24.ipynb
          git commit -m "Automated execution results"
          git push
